# Default values for ruoyi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domainName: yuoyi.example.com

hub: registry:5000/ruoyi
tag: v3.6.2

nacos:
  addr: nacos:8848