# Default values for ruoyi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domainName: ruoyi.example.com

hub: registry:5000/ruoyi
tag: v3.6.4

ruoyi:
  # file, minio
  storage: "file"
  minio:
    storageClassName: "nfs-client"
    auth:
      accessKey: "uig8ooMoqu6feek7Eefo"
      secretKey: "iekuenaa5uWaiqu9apeenaichieh6ahm6eilahfa"
    image:
      repository: minio/minio
      tag: RELEASE.2021-03-12T00-00-47Z
  sentinel:
    enable: true

redis:
  type: internal
  internal:
    storageClassName: "nfs-client"
    image:
      repository: redis
      tag: 6.2.6-alpine
  external:
    addr: "192.168.0.2:6379"
    password: ""


mysql:
  type: internal
  phpmyadmin: 
    enable: true
    repository: phpmyadmin
    tag: 5.2.1-apache
  internal:
    storageClassName: "nfs-client"
    image:
      repository: mysql
      tag: 5.7.44
  external:
    addr: "192.168.0.2:3306"
    username: ""
    password: ""

nacos:
  type: internal
  internal:
    storageClassName: "nfs-client"
    image:
      repository: nacos/nacos-server
      tag: v2.2.0
  external:
    addr: "192.168.0.2:8848"