apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-auth
  labels:
    project: ruoyi
data:
  config.yml: |-
    # Tomcat
    server: 
      port: 9200

    # Spring
    spring: 
      application:
        # 应用名称
        name: ruoyi-auth
      profiles:
        # 环境配置
        active: dev
      cloud:
        nacos:
          discovery:
            # 服务注册地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
          config:
            # 配置中心地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
            # 配置文件格式
            file-extension: yml
            # 共享配置
            shared-configs:
              - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-auth
  labels:
    project: ruoyi
spec:
  selector:
    app: ruoyi-auth
  ports:
    - name: tcp-9200
      port: 9200
      targetPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-auth
  labels:
    app: ruoyi-auth
    project: ruoyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-auth
  template:
    metadata:
      labels:
        app: ruoyi-auth
    spec:
      volumes:
        - name: ruoyi-auth
          configMap:
            defaultMode: 0755
            name: ruoyi-auth
      containers:
        - name: ruoyi-auth
          image: "{{ .Values.hub }}/ruoyi-auth:{{ .Values.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: ruoyi-auth
              mountPath: /app/config.yml
              subPath: config.yml
          ports:
            - name: tcp-9200
              containerPort: 9200
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9200
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9200
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: TZ
              value: "Asia/Shanghai"