---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ruoyi
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /nacos
            pathType: Prefix
            backend:
              service:
                name: nacos
                port:
                  number: 8848
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: ruoyi-gateway
                port:
                  number: 8080
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: ruoyi-visual-monitor
                port:
                  number: 9100
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruoyi-ui
                port:
                  number: 80
