---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: yuoyi
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: yuoyi.example.com
      http:
        paths:
          - path: /nacos
            pathType: Prefix
            backend:
              service:
                name: nacos
                port:
                  number: 8848
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: ruoyi-gateway
                port:
                  number: 8080
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruoyi-ui
                port:
                  number: 80
