apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-modules-gen
  labels:
    project: ruoyi
data:
  config.yml: |-
    # Tomcat
    server:
      port: 9202

    # Spring
    spring: 
      application:
        # 应用名称
        name: ruoyi-gen
      profiles:
        # 环境配置
        active: dev
      cloud:
        nacos:
          discovery:
            # 服务注册地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
          config:
            # 配置中心地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
            # 配置文件格式
            file-extension: yml
            # 共享配置
            shared-configs:
              - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-modules-gen
spec:
  selector:
    app: ruoyi-modules-gen
  ports:
    - name: tcp-9202
      port: 9202
      targetPort: 9202

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-modules-gen
  labels:
    app: ruoyi-modules-gen
    project: ruoyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-modules-gen
  template:
    metadata:
      labels:
        app: ruoyi-modules-gen
        project: ruoyi
    spec:
      volumes:
        - name: ruoyi-modules-gen
          configMap:
            defaultMode: 0755
            name: ruoyi-modules-gen
      initContainers:
        - name: wait-for-nacos
          image: buxiaomo/curl:8.2.1
          command:
            - "sh"
            - "-c"
            - |
              for i in $(seq 1 300);do
                  curl -s http://nacos:8848 -o /dev/null
                  if [ $? = "0" ];then
                      echo "nacos is initialized"
                      exit 0
                  fi
                  echo "nacos service is not initialized, waiting 1s... ($i/300)"
                  sleep 1
              done
      containers:
        - name: ruoyi-modules-gen
          image: "{{ .Values.hub }}/ruoyi-modules-gen:{{ .Values.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: ruoyi-modules-gen
              mountPath: /app/config.yml
              subPath: config.yml
          ports:
            - name: tcp-9202
              containerPort: 9202
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9202
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9202
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "5m"
              memory: "800Mi"
          env:
            - name: TZ
              value: "Asia/Shanghai"