apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-modules-job
data:
  config.yml: |-
    # Tomcat
    server:
      port: 9203

    # Spring
    spring: 
      application:
        # 应用名称
        name: ruoyi-job
      profiles:
        # 环境配置
        active: dev
      cloud:
        nacos:
          discovery:
            # 服务注册地址
            server-addr: {{ .Values.nacos.addr }}
          config:
            # 配置中心地址
            server-addr: {{ .Values.nacos.addr }}
            # 配置文件格式
            file-extension: yml
            # 共享配置
            shared-configs:
              - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-modules-job
spec:
  selector:
    app: ruoyi-modules-job
  ports:
    - name: tcp-9203
      port: 9203
      targetPort: 9203

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-modules-job
  labels:
    app: ruoyi-modules-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-modules-job
  template:
    metadata:
      labels:
        app: ruoyi-modules-job
    spec:
      volumes:
        - name: ruoyi-modules-job
          configMap:
            defaultMode: 0755
            name: ruoyi-modules-job
      containers:
        - name: ruoyi-modules-job
          image: "{{ .Values.hub }}/ruoyi-modules-job:{{ .Values.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: ruoyi-modules-job
              mountPath: /app/config.yml
              subPath: config.yml
          ports:
            - name: tcp-9203
              containerPort: 9203
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9203
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9203
          env:
            - name: TZ
              value: "Asia/Shanghai"