apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-modules-file
data:
  config.yml: |-
    # Tomcat
    server:
      port: 9300

    # Spring
    spring: 
      application:
        # 应用名称
        name: ruoyi-file
      profiles:
        # 环境配置
        active: dev
      cloud:
        nacos:
          discovery:
            # 服务注册地址
            server-addr: {{ .Values.nacos.addr }}
          config:
            # 配置中心地址
            server-addr: {{ .Values.nacos.addr }}
            # 配置文件格式
            file-extension: yml
            # 共享配置
            shared-configs:
              - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}

---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-modules-file
spec:
  selector:
    app: ruoyi-modules-file
  ports:
    - name: tcp-9300
      port: 9300
      targetPort: 9300

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-modules-file
  labels:
    app: ruoyi-modules-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-modules-file
  template:
    metadata:
      labels:
        app: ruoyi-modules-file
    spec:
      volumes:
        - name: ruoyi-modules-file
          configMap:
            defaultMode: 0755
            name: ruoyi-modules-file
      containers:
        - name: ruoyi-modules-file
          image: "{{ .Values.hub }}/ruoyi-modules-file:{{ .Values.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: ruoyi-modules-file
              mountPath: /app/config.yml
              subPath: config.yml
          ports:
            - name: tcp-9300
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9300
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9300
          env:
            - name: TZ
              value: "Asia/Shanghai"