{{ if .Values.mysql.phpmyadmin.enable }}
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: tcp-80
      port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: "{{ .Values.mysql.phpmyadmin.repository }}:{{ .Values.mysql.phpmyadmin.tag }}"
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 80
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: PMA_HOST
              value: {{ if eq .Values.mysql.type "internal" }}mysql{{ else }}{{ .Values.mysql.external.addr }}{{end}}
            - name: PMA_USER
              value: {{ if eq .Values.mysql.type "internal" }}root{{ else }}{{ .Values.mysql.external.username }}{{end}}

{{ end }}