apiVersion: v1
kind: ConfigMap
metadata:
  name: ruoyi-visual-monitor
  labels:
    project: ruoyi
data:
  config.yml: |-
    # Tomcat
    server:
      port: 9100

    # Spring
    spring: 
      application:
        # 应用名称
        name: ruoyi-monitor
      profiles:
        # 环境配置
        active: dev
      cloud:
        nacos:
          discovery:
            # 服务注册地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
          config:
            # 配置中心地址
            server-addr: {{ if eq .Values.nacos.type "internal" }}nacos:8848{{else}}{{ .Values.nacos.external.addr }}{{end}}
            # 配置文件格式
            file-extension: yml
            # 共享配置
            shared-configs:
              - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
---
apiVersion: v1
kind: Service
metadata:
  name: ruoyi-visual-monitor
  labels:
    project: ruoyi
spec:
  selector:
    app: ruoyi-visual-monitor
  type: NodePort
  ports:
    - name: tcp-9100
      port: 9100
      targetPort: 9100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruoyi-visual-monitor
  labels:
    app: ruoyi-visual-monitor
    project: ruoyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruoyi-visual-monitor
  template:
    metadata:
      labels:
        app: ruoyi-visual-monitor
    spec:
      volumes:
        - name: ruoyi-visual-monitor
          configMap:
            defaultMode: 0755
            name: ruoyi-visual-monitor
      containers:
        - name: ruoyi-visual-monitor
          image: "{{ .Values.hub }}/ruoyi-visual-monitor:{{ .Values.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: ruoyi-visual-monitor
              mountPath: /app/config.yml
              subPath: config.yml
          ports:
            - name: tcp-9100
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9100
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9100
          # resources:
          #   limits:
          #     cpu: "2"
          #     memory: "1Gi"
          #   requests:
          #     memory: "512Mi"
          env:
            - name: TZ
              value: "Asia/Shanghai"